### ISSUE TITLE
Adding a probe

### ISSUE THREAD

**Issue by 1623664** [quarkslab/irma#26]
When you add a probe in Windows7 and Ubuntu there is one error:
Traceback (most recent call last):
  File "./venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/app/utils.py", line 235, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/irma/irma-probe/current/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/irma/irma-probe/current/probe/tasks.py", line 103, in <module>
    p.plugin_mimetype_regexp)
  File "/opt/irma/irma-probe/current/probe/controllers/braintasks.py", line 32, in register_probe
    args=[name, display_name, category, mimetype_regexp])
  File "/opt/irma/irma-probe/current/probe/helpers/celerytasks.py", line 31, in async_call
    raise IrmaTaskError("Celery error - {0}".format(taskname))
lib.irma.common.exceptions.IrmaTaskError: Celery error - register_probe

what am I doing wrong.

**Comment by ch0k0bn** [comment]
Its a celery error, your settings in probe/config.ini are probably not correct (check broker_brain host address and/or credentials).

**Comment by 1623664** [comment]
[log]
syslog = 10


[probe]
name = esetnod32

[broker_probe]
host = 172.16.1.30
port = 5672
vhost = esetnod32
username = irma
password = 1

[broker_brain]
host = 172.16.1.30
port = 5672
vhost = mqbrain
username = brain
password = brain
queue = brain

[ftp_brain]
host = 172.16.1.30
auth = password
username = probe
password = probe

[ssl_config]
activate_ssl = no
ca_certs =
keyfile =
certfile =

probe/config.ini

**Comment by ch0k0bn** [comment]
seems ok for broker_brain part, the broker_probe is a bit weird, its supposed to be a global account for all probes 'vhost=esetnod32 username=irma password=1' is correct ?

is 172.16.1.30 accessible (do you ping it ?), could you double check your credentials. Could you also add "debug = 1" in the probe.ini log section under "syslog = 10" and retry launching the irma launcher?

**Comment by 1623664** [comment]
ping 172.16.1.30 there. Changed [broker_probe] vhost = mqprobe. The result is the same. Do I have to configure the brain?

**Comment by 1623664** [comment]
Thanks figured out the problem was the lack of communication))) 
There are questions about probe Drweb and Kaspersky, can help?))

**Comment by ch0k0bn** [comment]
sure, will be better in a new issue
